### ISSUE TITLE
PortAudio revision

### ISSUE THREAD

**Issue by pracucci** [spatialaudio/portaudio-binaries#1]
I suggest you to add the revision number of the PortAudio sources you compiled. I guess it's the `SVN rev 1919` but I'm not 100% sure just looking at `README.md`.

**Comment by mgeier** [comment]
Thanks for the hint, can you please have a look at #2?

The PortAudio version can be found here: https://github.com/mxe/mxe/blob/98a5771690279ebe89ac1b5134f02d4864cefa6b/src/portaudio.mk, it was (and I think still is) `v19_20140130`, which seems to be the latest "official" release, right?

Whenever (if ever?) there's a new PortAudio release, I'll wait for MXE to catch up and then I'll create new binaries.

**Comment by pracucci** [comment]
Ok thanks for the update. IMO would be easier if you simply specify `v19_20140130` in the `README.md` (just an hint).

**Comment by mgeier** [comment]
You're right, I added the info.
