### ISSUE TITLE
libportaudio64bit.dll exports a few MSVCRT symbols 

### ISSUE THREAD

**Issue by DavidC-75** [spatialaudio/portaudio-binaries#11]
Hi,

I'm not entirely sure what's going on. 
For a weird reason, some MSVCRT symbols have been included in, and are exported by the the pre-generated [libportaudio64bit.dll](https://github.com/spatialaudio/portaudio-binaries/blob/master/libportaudio64bit.dll) 

`dumpbin /exports libportaudio64bit.dll`

```
    992  3DF 00032F30 mbrlen
    993  3E0 00032D90 mbrtowc
    994  3E1 00032E00 mbsrtowcs
   1112  457 00033180 wcrtomb
   1113  458 000331C0 wcsrtombs
```

Needless to say, this is causing issues at link time, due to multiple definitions of the same symbol.

I believe this is not an issue with portaudio itself, but rather some issue in MXE, and even more specifically an issue in the MingW64 libraries that ship with the MXE version used to generate the portaudio binaries.

Using [the very same MXE version](https://github.com/mxe/mxe/tree/6d90c4ce068be5312d762f1a5e6a64d610e0e8ca ) that was used to generate the portaudio binaries, I observed the same effect when building [bzip2 1.0.8](https://www.sourceware.org/bzip2/) (see more details [here](https://stackoverflow.com/questions/71073127/why-would-a-cross-compiled-dll-export-symbols-already-defined-in-msvcrt))
With bzip2, I noticed that these unexpected symbols would disappear and would no longer be exported when using a more recent version of MXE.

It would be nice to re-generate the portaudio binaries too using a more recent MXE (not necessarily with a more recent version of gcc, but rather with a more recent version of the MingW64 libraries), just so these symbols go away and so they don't cause any conflicts at link time.

**Comment by mgeier** [comment]
Thanks for reporting this!

I've created a fresh set of DLLs in #12.

Can you please check if this fixes the problem?

**Comment by DavidC-75** [comment]
Thanks for the fresh build !!
The MSVCRT symbols have certainly disappeared and are no longer exported by the DLLs (as expected).
I can see that some new symbols are exported though:
       
         65   40 000444E0 GUID_DEVINTERFACE_HIDDEN_VOLUME
         68   43 00044510 GUID_DEVINTERFACE_SCM_PHYSICAL_DEVICE
         70   45 00044530 GUID_DEVINTERFACE_SERVICE_VOLUME
         71   46 00044540 GUID_DEVINTERFACE_SES
         74   49 00044570 GUID_DEVINTERFACE_UNIFIED_ACCESS_RPMB
         75   4A 00044580 GUID_DEVINTERFACE_VMLUN
         77   4C 000445A0 GUID_DEVINTERFACE_WRITEONCEDISK
         78   4D 000445B0 GUID_DEVINTERFACE_ZNSDISK
        165   A4 00044B20 GUID_SCM_PD_HEALTH_NOTIFICATION
        166   A5 00044B30 GUID_SCM_PD_PASSTHROUGH_INVDIMM
        761  2F8 000470E0 PKEY_DeviceInterface_FriendlyName
        762  2F9 00047100 PKEY_Device_DeviceDesc
       1019  3FA 00037990 pthread_attr_getstack
       1028  403 000379B0 pthread_attr_setstack

Is this the sign of a slightly different code base perhaps ? or is it only a consequence of using a different toolchaim to build the binaries ?

**Comment by mgeier** [comment]
I have no idea, sorry.

There might be some missing linker options when creating the DLLs (https://github.com/spatialaudio/portaudio-binaries/blob/master/README.md#dlls-for-windows-32-bit-and-64-bit)?
It's a strange mix of static and dynamic ... I've found those instructions by a lot of trial and error because I don't really have a deep understanding how any of this works.

Do the new (unexpected) symbols lead to linker errors?

If the MXE-based workflow is too limited, we could also try to build the DLLs with Github Actions with an actual Windows toolchain. However, I currently don't have the energy to look into this, and my Windows knowledge is very limited.

**Comment by DavidC-75** [comment]
> Do the new (unexpected) symbols lead to linker errors?

Not at all - No issues that I can see so far.
I think the MXE-based flow works really well - I was just wondering why these new symbols suddenly appeared, but it could well be just because you're not using a DEF file to control specifically which symbols are exported by the DLL, so a default mechanism is used instead... (which is fine really)

**Comment by mgeier** [comment]
So are the DLLs from #12 better than the old ones?
Should I merge #12 or is there something else to do?

> it could well be just because you're not using a DEF file to control specifically which symbols are exported by the DLL

I don't know what a DEF file is nor how to create one, nor do I care, TBH.

If you tell me how to do it (or better yet, if you provide a PR) I'm happy to include it, but I'm not willing to do any research into that Windows stuff.

**Comment by DavidC-75** [comment]
> So are the DLLs from #12 better than the old ones? 

From my limited perspective, I would say yes. This new build certainly addresses the issue that was raised initially (MSVCRT symbols were being exported)

> Should I merge #12 or is there something else to do?

I sincerely appreciate your help and the time you spent rebuilding these new binaries, but it's hard for me to recommend any merge. My usage of portaudio is very limited in scope, and there might be hidden issues that I haven't seen. If you do merge, I won't complain but someone else might ;-)

**Comment by mgeier** [comment]
> [...] there might be hidden issues that I haven't seen. If you do merge though, I won't complain but someone else might ;-)

I merely re-built the DLLs with the latest MXE.

Theoretically, a new bug might have been introduced to MXE in the meantime, but that's always a risk when updating software. I assume that more problems have been fixed than have been newly created.

And if not, that's life, then somebody will hopefully recognize it and create a new issue, and the cycle starts again ...
