### ISSUE TITLE
_PaUtil_FreeMemory Undefined Symbols when linking dylib on Mac OS

### ISSUE THREAD

**Issue by sibo7851** [spatialaudio/portaudio-binaries#13]
Hi there, the title is pretty self explanatory.  I'm getting a linker error for the _PaUtil_FreeMemory function which is defined in pa_unix_util.c 

This is on Intel Mac OS 10.15.7

I'm going to try some of the older binaries to see if they fix this.  Thanks.

**Comment by mgeier** [comment]
Can you please provide a minimal example and the exact linker error message?

**Comment by mgeier** [comment]
Closing due to lack of response.
