### ISSUE TITLE
Add support for macos arm64

### ISSUE THREAD

**Issue by gesellkammer** [spatialaudio/portaudio-binaries#15]
It would be nice if macos arm64 (M1, M2) would also be supported. If needed, I can provide macos universal builds of portaudio

**Comment by mgeier** [comment]
I was under the impression that the provided `.dylib` already supports arm64, see #10.

While you are testing this, you might as well have a look at the binaries in #14, which are generated via Github Actions, but those should as well support arm64.

**Comment by gesellkammer** [comment]
You are right, the errors I saw in CI were due to a conflict with a x86_64 portaudio library installed by a third party. Sorry for the noise.
