### ISSUE TITLE
Are you able to provide for Linux also?

### ISSUE THREAD

**Issue by stevehjohn** [spatialaudio/portaudio-binaries#17]
As the title says, it would be nice if you could provide for Linux (x64 and ARM) also.

Fully understand if it's not worth the work.

Thanks.

**Comment by mgeier** [comment]
I don't have a need for Linux binaries myself and I have no experience building libraries that are compatible with many Linux distributions. So I won't do it.

But you or anyone else can do it! Just add a Linux section to the already existing CI setup: https://github.com/spatialaudio/portaudio-binaries/blob/master/.github/workflows/build-libs.yml

I'm open for PRs!

**Comment by stevehjohn** [comment]
Completely understood.
