### ISSUE TITLE
Debug libraries

### ISSUE THREAD

**Issue by pracucci** [spatialaudio/portaudio-binaries#3]
Would be great if you could provide the libraries, both compiled in release and debug mode. The debug mode would be super helpful if it contains the PortAudio debug logs, so that a developer can switch it based upon its needs.

**Comment by mgeier** [comment]
I don't know how to do that in MXE, I don't even know what "debug" is supposed to mean exactly.

Do I have to set `PA_ENABLE_DEBUG_OUTPUT`?
Add debug symbols?
Disable optimization?

I only found this open issue @ MXE: https://github.com/mxe/mxe/issues/301

If you tell me how I can do this (and if it doesn't make everything too complicated), I'll gladly add this!

**Comment by pracucci** [comment]
You should just set `PA_ENABLE_DEBUG_OUTPUT` and `PA_LOG_API_CALLS` then recompile. Such libraries could be named ie. `portaudio-debug-32bit.dll`, ...

**Comment by mgeier** [comment]
I added DLLs in #4, but I didn't test if they actually work as expected.

@pracucci: can you please test them?

**Comment by mgeier** [comment]
@pracucci Do you still need this?

**Comment by pracucci** [comment]
Sorry for the very late reply. We've used it (successfully). Any chance to merge them to master?

**Comment by mgeier** [comment]
Sure, I was just waiting for your response.
Did you try both the 32-bit and the 64-bit DLLs?

**Comment by pracucci** [comment]
32bit only

**Comment by mgeier** [comment]
Could you please test the other one, too?

**Comment by pracucci** [comment]
Unfortunately our app is 32-bit only right now, that why I can't test your
64-bit libraries right now.

2016-03-31 10:18 GMT+02:00 Matthias Geier <notifications@github.com>:
