### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by mscuthbert** [spatialaudio/portaudio-binaries#5]
Hi folks -- these are great resources; I'll be pointing my students here in the future.  Just a suggestion, since these will probably be used by portaudio newbies: can the README.md begin with instructions of where to put these binaries on Windows and OS X?  Thanks!

**Comment by mgeier** [comment]
Actually, I didn't intend this repo for end users but rather for people who want to distribute the libraries together with their programs.

I'm using it myself here: https://github.com/spatialaudio/python-sounddevice (in the `_sounddevice_data` submodule).

I don't know where those files should "normally" be copied to on OSX, even less on Windows.

But anyway, if you have suggestions for improving the instructions, feel free to make a pull request!
